import { AiOutlineClose } from "react-icons/ai";
import { TbMenu } from "react-icons/tb";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import Footer from "../components/Footer";
import TabGroup from "../components/Tabs";
import Logo from "../ux/logo/logo_seniorita.svg";
import ImgService from "../services/imgService"

const inter = Inter({ subsets: ["latin"] });

export default function Home({ mappedPhoto }) {
  const [toggleMenu, setToggleMenu] = useState(false);

  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className=" h-[70px] z-10 ">
        <div className="h-full w-full flex justify-between items-center px-5 ">
          <div className=" gap-1 text-4xl opacity-0 hidden md:flex"></div>
          <div >
            <Logo className="w-12 h-12" />
          </div>
          <div
            onClick={() => setToggleMenu(!toggleMenu)}
            className="hover:opacity-80 cursor-pointer transition-all items-center w-5 md:opacity-0"
          >
            {!toggleMenu ? (
              <TbMenu className="text-2xl" />
            ) : (
              <AiOutlineClose className="text-2xl" />
            )}
          </div>
        </div>
      </header>
      <main className=" md:pt-[30px] ">
        <TabGroup toggleMenu={toggleMenu} photos={mappedPhoto} />
      </main>
      <Footer />
    </div>
  );
}

export async function getServerSideProps() {
  const imgService = new ImgService();
  const photos = await imgService.getCachePhotos();

  return {
    props: {
      mappedPhoto: photos
    }
  };
}


