import { AiOutlineClose } from "react-icons/ai";
import { TbMenu } from "react-icons/tb";

import icons from "../pages/materials";

import Head from "next/head";
import { Inter } from "@next/font/google";
import Tabs from "./Tabs";

import allImages from "./photo";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const firstPhoto = allImages.slice(0, allImages.length / 2);
const secondPhoto = allImages.slice(firstPhoto.length, allImages.length + 1);

export default function Home() {
  const [toggleMenu, setToggleMenu] = useState(false);

  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=" h-[70px] z-10">
        <div className="h-full w-full flex justify-between items-center px-5 ">
          <div className=" gap-1 text-4xl opacity-0 hidden md:flex"></div>
          <h2 className="text-2xl uppercase tracking-semibold">senorita</h2>
          <div
            onClick={() => setToggleMenu(!toggleMenu)}
            className="hover:opacity-80 cursor-pointer transition-all items-center w-5 md:opacity-0"
          >
            {!toggleMenu ? (
              <TbMenu className="text-2xl" />
            ) : (
              <AiOutlineClose className="text-2xl" />
            )}
          </div>
        </div>
      </header>
      <main className=" md:pt-[30px] ">
        <div>
          <Tabs
            allImages={allImages}
            firstPhoto={firstPhoto}
            secondPhoto={secondPhoto}
            toggleMenu={toggleMenu}
          />
        </div>
      </main>
      <footer className="h-[100px] mb-5 flex items-center justify-center relative">
        <div className="absolute w-100  flex justify-center  gap-2 text-2xl z-20">
          {icons.map((icon, idx) => (
            <div
              key={idx}
              className="border-2 border-slate-800 rounded-full p-2 md:p-3 bg-slate-50"
            >
              {icon}
            </div>
          ))}
        </div>
        <div className="w-full border border-b-slate-800 opacity-30"></div>
      </footer>
    </div>
  );
}
